name: newzen
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.11.0
  flutter_vision: ^1.1.4
  camera: ^0.11.0
  image_picker: ^1.1.2
  image: ^4.2.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/device/
    - assets/images/functions/
    - assets/images/home/
    - assets/images/info/
    - assets/images/auth/
    - assets/icons/device/
    - assets/icons/functions/
    - assets/icons/home/
    - assets/icons/point/
    - assets/icons/progress_circle/
    - assets/icons/status/
    - assets/icons/tuc/
    - assets/models/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  fonts:
    - family: Lg
      fonts:
        - asset: assets/fonts/LGEITextTTF-Light.ttf
        - asset: assets/fonts/LGEITextTTF-Regular.ttf
        - asset: assets/fonts/LGEITextTTF-SemiBold.ttf
        - asset: assets/fonts/LGEITextTTF-Bold.ttf