name: newzen
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  camera: ^0.10.3+2
  flutter_tflite: ^1.0.1
  flutter_svg: ^2.0.0
  tflite_flutter: ^0.11.0
  tflite_flutter_helper_plus: ^0.0.2
  image: ^3.3.0
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/yolov2_tiny.tflite
    - assets/yolov2_tiny.txt
    - assets/ssd_mobilenet.tflite
    - assets/ssd_mobilenet.txt
    - assets/mobilenet_v1_1.0_224.tflite
    - assets/mobilenet_v1_1.0_224.txt
    - assets/posenet_mv1_075_float_from_checkpoints.tflite
    - assets/models/food_detect.tflite
    - assets/models/food_labelmap.txt
    - assets/models/yes_no_food_info.txt
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Lg
      fonts:
        - asset: assets/fonts/LGEITextTTF-Light.ttf
        - asset: assets/fonts/LGEITextTTF-Regular.ttf
        - asset: assets/fonts/LGEITextTTF-SemiBold.ttf
        - asset: assets/fonts/LGEITextTTF-Bold.ttf
